export const foodList = [
  {
    id: Math.random(),
    title: 'وجبة فطار',
    description: 'وجبة فطار ممتازة جدا',
    img: '1.png',
    category: 'فطار',
    price: '50 جنيه',
  },
  {
    id: Math.random(),
    title: 'وجبة غداء',
    description: 'وجبة غداء ممتازة جدا',
    img: '2.png',
    category: 'غداء',
    price: '30 جنيه',
  },
  {
    id: Math.random(),
    title: 'وجبة عشاء',
    description: 'وجبة عشاء ممتازة جدا',
    img: '3.png',
    category: 'عشاء',
    price: '70 جنيه',
  },
  {
    id: Math.random(),
    title: 'وجبة فطار',
    description: 'وجبة فطار ممتازة جدا',
    img: '1.png',
    category: 'فطار',
    price: '40 جنيه',
  },
  {
    id: Math.random(),
    title: 'وجبة غداء',
    description: 'وجبة غداء ممتازة جدا',
    img: '2.png',
    category: 'غداء',
    price: '100 جنيه',
  },
  {
    id: Math.random(),
    title: 'وجبة عشاء',
    description: 'وجبة عشاء ممتازة جدا',
    img: '3.png',
    category: 'عشاء',
    price: '80 جنيه',
  },
];
